In [101]:
import pandas as pd
import numpy as np

import torch
from torch.utils.data import Dataset

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.src.callbacks import EarlyStopping
from keras.src.layers import Conv1D, GlobalMaxPooling1D

from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments

import warnings
warnings.filterwarnings("ignore")

import pickle

### Подготовка данных

In [102]:
df = pd.read_csv("data/intents_train.csv")

df['text'] = df['text'].str.lower()

le = LabelEncoder()
df['intent_id'] = le.fit_transform(df['intent'])

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(df['text'])

X = tokenizer.texts_to_sequences(df['text'])
X = pad_sequences(X, maxlen=20)

y = df['intent_id']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

### RNN

In [103]:
rnn = Sequential([
    Embedding(5000, 64),
    SimpleRNN(32),
    Dense(len(df['intent'].unique()), activation='softmax')
])

rnn.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
rnn.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=8,
)

Epoch 1/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.1867 - loss: 1.9344 - val_accuracy: 0.2105 - val_loss: 1.8848
Epoch 2/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4000 - loss: 1.7747 - val_accuracy: 0.3158 - val_loss: 1.8184
Epoch 3/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4800 - loss: 1.6525 - val_accuracy: 0.4737 - val_loss: 1.7391
Epoch 4/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7733 - loss: 1.5410 - val_accuracy: 0.5263 - val_loss: 1.6713
Epoch 5/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8533 - loss: 1.4348 - val_accuracy: 0.6842 - val_loss: 1.6070
Epoch 6/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8667 - loss: 1.3147 - val_accuracy: 0.5789 - val_loss: 1.5739
Epoch 7/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8800 - loss: 1.1937 - val_accuracy: 0.6316 - val_loss: 1.5124
Epoch 8/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9200 - loss: 1.0771 - val_accuracy: 0.5789 - val_loss: 1.4563
Epoch 9/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9733 - loss: 0.9541 - val_accuracy: 0.5789 - val_loss: 1.4197
Epoch 10/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9467 - loss: 0.8534 - val_accuracy: 0.5789 - val_loss: 1.3748
Epoch 11/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9600 - loss: 0.7460 - val_accuracy: 0.5789 - val_loss: 1.3135
Epoch 12/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.6541 - val_accuracy: 0.5789 - val_loss: 1.3039
Epoch 13/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9733 - loss: 0.5761 - val_accuracy: 0.6316 - val_loss: 1.2791
Epoch 14/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.4972 - val_accuracy: 0.5789 - val_loss: 1.2237
Epoch 15/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.4368 - val_accuracy: 0.6316 - val_loss: 1.2077
Epoch 16/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.3848 - val_accuracy: 0.6316 - val_loss: 1.2088
Epoch 17/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.3371 - val_accuracy: 0.5789 - val_loss: 1.1896
Epoch 18/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.3063 - val_accuracy: 0.6316 - val_loss: 1.1645
Epoch 19/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.2687 - val_accuracy: 0.6316 - val_loss: 1.1534
Epoch 20/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.2507 - val_accuracy: 0.6842 - val_loss: 1.1834

### LSTM

In [104]:
lstm = Sequential([
    Embedding(5000, 64),
    LSTM(32),
    Dense(len(df['intent'].unique()), activation='softmax')
])

lstm.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
lstm.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=8
)

Epoch 1/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.1867 - loss: 1.9345 - val_accuracy: 0.2632 - val_loss: 1.9116
Epoch 2/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1867 - loss: 1.8883 - val_accuracy: 0.2105 - val_loss: 1.8693
Epoch 3/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1867 - loss: 1.8356 - val_accuracy: 0.2105 - val_loss: 1.8165
Epoch 4/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1867 - loss: 1.7735 - val_accuracy: 0.2105 - val_loss: 1.7806
Epoch 5/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3600 - loss: 1.7158 - val_accuracy: 0.5263 - val_loss: 1.7489
Epoch 6/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4400 - loss: 1.6589 - val_accuracy: 0.1579 - val_loss: 1.7301
Epoch 7/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4667 - loss: 1.5947 - val_accuracy: 0.3158 - val_loss: 1.6897
Epoch 8/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5467 - loss: 1.5353 - val_accuracy: 0.6316 - val_loss: 1.6086
Epoch 9/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5467 - loss: 1.4284 - val_accuracy: 0.4211 - val_loss: 1.5486
Epoch 10/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7067 - loss: 1.3065 - val_accuracy: 0.5789 - val_loss: 1.4446
Epoch 11/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6800 - loss: 1.2131 - val_accuracy: 0.7368 - val_loss: 1.3690
Epoch 12/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7867 - loss: 1.0688 - val_accuracy: 0.6316 - val_loss: 1.3241
Epoch 13/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7733 - loss: 0.9402 - val_accuracy: 0.6842 - val_loss: 1.2036
Epoch 14/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7867 - loss: 0.8583 - val_accuracy: 0.7368 - val_loss: 1.1548
Epoch 15/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8400 - loss: 0.7297 - val_accuracy: 0.7368 - val_loss: 1.1101
Epoch 16/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8400 - loss: 0.6856 - val_accuracy: 0.7368 - val_loss: 1.0010
Epoch 17/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8933 - loss: 0.5953 - val_accuracy: 0.7895 - val_loss: 0.9351
Epoch 18/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8800 - loss: 0.5208 - val_accuracy: 0.6316 - val_loss: 1.0117
Epoch 19/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9200 - loss: 0.4766 - val_accuracy: 0.6842 - val_loss: 0.8354
Epoch 20/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9200 - loss: 0.4242 - val_accuracy: 0.7895 - val_loss: 0.7829

### BERT

In [105]:
train_texts, test_texts, train_labels, test_labels = train_test_split(
    df['text'].tolist(),
    df['intent_id'].tolist(),
    test_size=0.2,
    random_state=42
)

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=20
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=20
)

class IntentDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = IntentDataset(train_encodings, train_labels)
test_dataset = IntentDataset(test_encodings, test_labels)

In [106]:
bert = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=len(le.classes_)
)

training_args = TrainingArguments(
    num_train_epochs=20,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
)

trainer = Trainer(
    model=bert,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

trainer.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

TrainOutput(global_step=200, training_loss=0.42399986267089845, metrics={'train_runtime': 164.1891, 'train_samples_per_second': 9.136, 'train_steps_per_second': 1.218, 'total_flos': 13104752175000.0, 'train_loss': 0.42399986267089845, 'epoch': 20.0})

### Оценка моделей

In [107]:
result = pd.DataFrame(columns=['Model', 'Params', 'Accuracy', 'F1 Score'])

def evalute_model(model, X_test, y_test, type_name, framework='keras'):
    
    if framework == 'transformers':
        preds = model.predict(X_test)
        y_pred = np.argmax(preds.predictions, axis=1)
        params = str(trainer.model.bert).replace('\n', '').replace(' ', '')
    elif framework == 'keras':
        y_pred = model.predict(X_test)
        y_pred = np.argmax(y_pred, axis=1)
        params = model.get_config()
    else:
        raise ValueError("Unsupported framework")
    
    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    result.loc[len(result)] = [type_name, params, accuracy, f1]
    
    print("Accuracy:", accuracy)
    print("F1 Score:", f1)

In [108]:
evalute_model(rnn, X_test, y_test, 'RNN', framework='keras')
evalute_model(lstm, X_test, y_test, 'LSTM', framework='keras')
evalute_model(trainer, test_dataset, test_labels, 'BERT', framework='transformers')
result

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
Accuracy: 0.6842105263157895
F1 Score: 0.6758563074352547
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
Accuracy: 0.7894736842105263
F1 Score: 0.7479949874686717

Accuracy: 0.8947368421052632
F1 Score: 0.8962406015037594

,Model,Params,Accuracy,F1 Score
0,RNN,"{'name': 'sequential_15', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'layers': [{'module': 'keras.layers', 'class_name': 'InputLayer', 'config': {'batch_shape': (None, 20), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'input_layer_15', 'optional': False}, 'registered_name': None}, {'module': 'keras.layers', 'class_name': 'Embedding', 'config': {'name': 'embedding_15', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'input_dim': 5000, 'output_dim': 64, 'embeddings_initializer': {'module': 'keras.initializers', 'class_name': 'RandomUniform', 'config': {'seed': None, 'minval': -0.05, 'maxval': 0.05}, 'registered_name': None}, 'embeddings_regularizer': None, 'activity_regularizer': None, 'embeddings_constraint': None, 'mask_zero': False, 'quantization_config': None}, 'registered_name': None, 'build_config': {'input_shape': (None, 20)}}, {'module': 'keras.layers', 'class_name': 'SimpleRNN', 'config': {'name': 'simple_rnn_6', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'stateful': False, 'unroll': False, 'zero_output_for_mask': False, 'units': 32, 'activation': 'tanh', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'recurrent_initializer': {'module': 'keras.initializers', 'class_name': 'Orthogonal', 'config': {'seed': None, 'gain': 1.0}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'recurrent_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'recurrent_constraint': None, 'bias_constraint': None, 'dropout': 0.0, 'recurrent_dropout': 0.0}, 'registered_name': None, 'build_config': {'input_shape': (None, 20, 64)}}, {'module': 'keras.layers', 'class_name': 'Dense', 'config': {'name': 'dense_15', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 7, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'quantization_config': None}, 'registered_name': None, 'build_config': {'input_shape': (None, 32)}}], 'build_input_shape': (None, 20)}",0.684211,0.675856
1,LSTM,"{'name': 'sequential_16', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'layers': [{'module': 'keras.layers', 'class_name': 'InputLayer', 'config': {'batch_shape': (None, 20), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'input_layer_16', 'optional': False}, 'registered_name': None}, {'module': 'keras.layers', 'class_name': 'Embedding', 'config': {'name': 'embedding_16', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'input_dim': 5000, 'output_dim': 64, 'embeddings_initializer': {'module': 'keras.initializers', 'class_name': 'RandomUniform', 'config': {'seed': None, 'minval': -0.05, 'maxval': 0.05}, 'registered_name': None}, 'embeddings_regularizer': None, 'activity_regularizer': None, 'embeddings_constraint': None, 'mask_zero': False, 'quantization_config': None}, 'registered_name': None, 'build_config': {'input_shape': (None, 20)}}, {'module': 'keras.layers', 'class_name': 'LSTM', 'config': {'name': 'lstm_4', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'stateful': False, 'unroll': False, 'zero_output_for_mask': False, 'units': 32, 'activation': 'tanh', 'recurrent_activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'recurrent_initializer': {'module': 'keras.initializers', 'class_name': 'Orthogonal', 'config': {'seed': None, 'gain': 1.0}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'unit_forget_bias': True, 'kernel_regularizer': None, 'recurrent_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'recurrent_constraint': None, 'bias_constraint': None, 'dropout': 0.0, 'recurrent_dropout': 0.0, 'seed': None}, 'registered_name': None, 'build_config': {'input_shape': (None, 20, 64)}}, {'module': 'keras.layers', 'class_name': 'Dense', 'config': {'name': 'dense_16', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 7, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'quantization_config': None}, 'registered_name': None, 'build_config': {'input_shape': (None, 32)}}], 'build_input_shape': (None, 20)}",0.789474,0.747995
2,BERT,"BertModel((embeddings):BertEmbeddings((word_embeddings):Embedding(30522,768,padding_idx=0)(position_embeddings):Embedding(512,768)(token_type_embeddings):Embedding(2,768)(LayerNorm):LayerNorm((768,),eps=1e-12,elementwise_affine=True)(dropout):Dropout(p=0.1,inplace=False))(encoder):BertEncoder((layer):ModuleList((0-11):12xBertLayer((attention):BertAttention((self):BertSelfAttention((query):Linear(in_features=768,out_features=768,bias=True)(key):Linear(in_features=768,out_features=768,bias=True)(value):Linear(in_features=768,out_features=768,bias=True)(dropout):Dropout(p=0.1,inplace=False))(output):BertSelfOutput((dense):Linear(in_features=768,out_features=768,bias=True)(LayerNorm):LayerNorm((768,),eps=1e-12,elementwise_affine=True)(dropout):Dropout(p=0.1,inplace=False)))(intermediate):BertIntermediate((dense):Linear(in_features=768,out_features=3072,bias=True)(intermediate_act_fn):GELUActivation())(output):BertOutput((dense):Linear(in_features=3072,out_features=768,bias=True)(LayerNorm):LayerNorm((768,),eps=1e-12,elementwise_affine=True)(dropout):Dropout(p=0.1,inplace=False)))))(pooler):BertPooler((dense):Linear(in_features=768,out_features=768,bias=True)(activation):Tanh()))",0.894737,0.896241

### Предсказание / Сохранение модели

In [109]:
test = pd.read_csv("data/intents_test.csv")
test['text'] = test['text'].str.lower()

test_encodings = tokenizer(
    test['text'].tolist(),
    truncation=True,
    padding=True,
    max_length=20
)

test_dataset = IntentDataset(test_encodings, [0]*len(test))
preds = trainer.predict(test_dataset)
test['predicted_intent_id'] = np.argmax(preds.predictions, axis=1)
test['predicted_intent'] = le.inverse_transform(test['predicted_intent_id'])
test[['text', 'predicted_intent']].to_csv("data/predictions.csv", index=False)

# Pytorch
torch.save(trainer.model.state_dict(), "data/bert_intent_model.pth")

# Pickle
with open("data/model.pkl", "wb") as f:
    pickle.dump(trainer.model.state_dict(), f)

In [118]:
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=7
)

with open("data/model.pkl", "rb") as f:
    state_dict = pickle.load(f)

model.load_state_dict(state_dict)
# model.load_state_dict(torch.load("data/bert_intent_model.pth"))

model.eval()
with torch.no_grad():
    inputs = tokenizer(
        test_texts,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=20
    )
    outputs = model(**inputs)
    predicted_label_id = torch.argmax(outputs.logits, dim=1)
    
    print('Accuracy:', accuracy_score(y_test, predicted_label_id))
    print('F1 Score:', f1_score(y_test, predicted_label_id, average='weighted'))

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Accuracy: 0.8947368421052632
F1 Score: 0.8962406015037594

### CNN

In [111]:
cnn = Sequential([
    Embedding(5000, 64),
    Conv1D(32, kernel_size=3, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(len(df['intent'].unique()), activation='softmax')
])

cnn.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=8,
    callbacks=[
        EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    ]
)

evalute_model(cnn, X_test, y_test, 'CNN', framework='keras')

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.1733 - loss: 1.9241 - val_accuracy: 0.2105 - val_loss: 1.9138
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2933 - loss: 1.8601 - val_accuracy: 0.4211 - val_loss: 1.8829
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4800 - loss: 1.8050 - val_accuracy: 0.4211 - val_loss: 1.8504
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4933 - loss: 1.7545 - val_accuracy: 0.3158 - val_loss: 1.8163
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4800 - loss: 1.6986 - val_accuracy: 0.3158 - val_loss: 1.7836
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5200 - loss: 1.6390 - val_accuracy: 0.3684 - val_loss: 1.7514
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5867 - loss: 1.5752 - val_accuracy: 0.3684 - val_loss: 1.7160
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5867 - loss: 1.5151 - val_accuracy: 0.3684 - val_loss: 1.6779
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6267 - loss: 1.4396 - val_accuracy: 0.3684 - val_loss: 1.6400
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6667 - loss: 1.3616 - val_accuracy: 0.3684 - val_loss: 1.5967
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7200 - loss: 1.2820 - val_accuracy: 0.3684 - val_loss: 1.5533
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7867 - loss: 1.1975 - val_accuracy: 0.4211 - val_loss: 1.5072
Epoch 13/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8000 - loss: 1.1163 - val_accuracy: 0.4211 - val_loss: 1.4636
Epoch 14/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8267 - loss: 1.0320 - val_accuracy: 0.4211 - val_loss: 1.4239
Epoch 15/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8533 - loss: 0.9499 - val_accuracy: 0.5263 - val_loss: 1.3754
Epoch 16/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8533 - loss: 0.8654 - val_accuracy: 0.6316 - val_loss: 1.3290
Epoch 17/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8800 - loss: 0.7874 - val_accuracy: 0.6842 - val_loss: 1.2820
Epoch 18/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9200 - loss: 0.7062 - val_accuracy: 0.6842 - val_loss: 1.2420
Epoch 19/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9200 - loss: 0.6338 - val_accuracy: 0.6842 - val_loss: 1.1914
Epoch 20/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9467 - loss: 0.5644 - val_accuracy: 0.6842 - val_loss: 1.1386
Epoch 21/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9733 - loss: 0.5008 - val_accuracy: 0.6842 - val_loss: 1.0948
Epoch 22/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9733 - loss: 0.4435 - val_accuracy: 0.6842 - val_loss: 1.0470
Epoch 23/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9733 - loss: 0.3920 - val_accuracy: 0.6842 - val_loss: 1.0014
Epoch 24/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9733 - loss: 0.3473 - val_accuracy: 0.6842 - val_loss: 0.9596
Epoch 25/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9733 - loss: 0.3066 - val_accuracy: 0.6842 - val_loss: 0.9257
Epoch 26/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9733 - loss: 0.2712 - val_accuracy: 0.7368 - val_loss: 0.8867
Epoch 27/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9733 - loss: 0.2408 - val_accuracy: 0.7368 - val_loss: 0.8516
Epoch 28/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9733 - loss: 0.2164 - val_accuracy: 0.7368 - val_loss: 0.8195
Epoch 29/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9733 - loss: 0.1927 - val_accuracy: 0.7368 - val_loss: 0.7880
Epoch 30/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.1735 - val_accuracy: 0.7368 - val_loss: 0.7625
Epoch 31/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.1568 - val_accuracy: 0.7368 - val_loss: 0.7371
Epoch 32/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.1419 - val_accuracy: 0.7368 - val_loss: 0.7146
Epoch 33/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.1297 - val_accuracy: 0.7368 - val_loss: 0.6968
Epoch 34/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9867 - loss: 0.1184 - val_accuracy: 0.7895 - val_loss: 0.6777
Epoch 35/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9867 - loss: 0.1084 - val_accuracy: 0.7895 - val_loss: 0.6617
Epoch 36/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9867 - loss: 0.1006 - val_accuracy: 0.8421 - val_loss: 0.6449
Epoch 37/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.0935 - val_accuracy: 0.8421 - val_loss: 0.6320
Epoch 38/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0879 - val_accuracy: 0.8421 - val_loss: 0.6183
Epoch 39/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0824 - val_accuracy: 0.8421 - val_loss: 0.6057
Epoch 40/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0773 - val_accuracy: 0.8421 - val_loss: 0.5958
Epoch 41/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.0725 - val_accuracy: 0.8421 - val_loss: 0.5844
Epoch 42/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9867 - loss: 0.0687 - val_accuracy: 0.8947 - val_loss: 0.5755
Epoch 43/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0659 - val_accuracy: 0.8421 - val_loss: 0.5660
Epoch 44/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.0615 - val_accuracy: 0.8947 - val_loss: 0.5603
Epoch 45/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9867 - loss: 0.0584 - val_accuracy: 0.8947 - val_loss: 0.5537
Epoch 46/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0556 - val_accuracy: 0.8947 - val_loss: 0.5474
Epoch 47/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0536 - val_accuracy: 0.8947 - val_loss: 0.5400
Epoch 48/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0508 - val_accuracy: 0.8947 - val_loss: 0.5348
Epoch 49/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0484 - val_accuracy: 0.8947 - val_loss: 0.5293
Epoch 50/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0472 - val_accuracy: 0.8947 - val_loss: 0.5237
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Accuracy: 0.8947368421052632
F1 Score: 0.888888888888889